name: anyway_trip_application
description: "Anyway Trip Application - TTcoin proximity reward demo app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.34.5
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/coin.png
    - assets/images/anywaytrip.png
    - assets/images/icon1.png
    - assets/images/icon3.png
    - assets/images/icon4.png
    - assets/images/icon5.png
  
  fonts:
    - family: ITIM
      fonts:
      - asset: assets/fonts/Itim-Regular.ttf
